AWSTemplateFormatVersion: "2010-09-09"

Description: Updates the WLSConnectVoicemail roles with appropriate policies. Updated for 2024.09.01.

Parameters:
  ConnectInstanceAlias:
    Type: String
  ConnectInstanceARN:
    Type: String
  WLSConnectVoicemailGuidedFlowPresignerRole:
    Type: String
  WLSConnectVoicemailKVStoS3Role:
    Type: String
  WLSConnectVoicemailPackagerRole:
    Type: String
  WLSConnectVoicemailPresignerRole:
    Type: String
  WLSConnectVoicemailSESTemplateRole:
    Type: String
  WLSConnectVoicemailTranscriberRole:
    Type: String
  WLSConnectVoicemailTranscriberRoleArn:
    Type: String
    # Default: 'arn:aws:iam::209479304522:role/WLSConnectVoicemail3_Transcriber_Role_bolerotest'
  WLSConnectVoicemailTranscriberErrorRole:
    Type: String
  WLSConnectVoicemailS3RecordingsBucketArn:
    Type: String
  WLSConnectVoicemailS3TranscriptsBucketArn:
    Type: String
  WLSConnectVoicemailKVSStreamPrefix:
    Type: String
  ConnectCTRStreamARN:
    Type: String
  AWSRegion:
    Type: String
  WLSConnectVoicemailPresignerArn:
    Type: String
  EnableVMToConnectTask:
    Type: String
  EnableVMToEmail:
    Type: String
  EnableVMToConnectGuidedTask:
    Type: String
  VoicemailKeyArn:
    Type: String
  WLSConnectVoicemailPresignerAssumeRoleArn:
    Type: String
  WLSConnectVoicemailKVSStreamKMSVoicemailKeyArn:
    Type: String
    

Conditions:
  NonGuidedOptions: !Or
    - !Equals
      - !Ref EnableVMToConnectTask
      - 'yes'
    - !Equals
      - !Ref EnableVMToEmail
      - 'yes'
  AWSEmailEnabled: !Equals
    - !Ref EnableVMToEmail
    - 'yes'
  ConnectGuidedTasksEnabled: !Equals
    - !Ref EnableVMToConnectGuidedTask
    - 'yes'

Resources:
  WLSConnectVoicemailGuidedFlowPresignerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: ConnectGuidedTasksEnabled
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:GeneratePresignedUrl'
            Resource:
              !Join
                - ''
                - - !Ref WLSConnectVoicemailS3RecordingsBucketArn
                  - '/*'
      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_Guide_Presigner_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailGuidedFlowPresignerRole

  WLSConnectVoicemailKVStoS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'kinesisvideo:ListFragments'
              - 'kinesisvideo:GetMediaForFragmentList'
              - 'kinesisvideo:GetDataEndpoint'
            Resource:
              !Join
                - ''
                - - 'arn:aws:kinesisvideo:'
                  - !Ref AWSRegion
                  - ':'
                  - !Ref AWS::AccountId
                  - ':stream/'
                  - !Ref WLSConnectVoicemailKVSStreamPrefix
                  - '*'
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:PutObjectTagging'
            Resource:
              !Join
                - ''
                - - !Ref WLSConnectVoicemailS3RecordingsBucketArn
                  - '/*'
          - Effect: Allow
            Action:
              - 'kinesis:ListShards'
              - 'kinesis:GetRecords'
              - 'kinesis:DescribeStream'
              - 'kinesis:DescribeStreamSummary'
              - 'kinesis:SubscribeToShard'
              - 'kinesis:GetShardIterator'
              - 'kinesis:ListShards'
              - 'kinesis:ListStreams'
            Resource: !Ref ConnectCTRStreamARN    
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:GenerateDataKey'
            Resource:
              - !Ref VoicemailKeyArn
              - !Ref WLSConnectVoicemailKVSStreamKMSVoicemailKeyArn
   
      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_KVS_to_S3_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailKVStoS3Role

  WLSConnectVoicemailPackagerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'connect:DescribeUser'
              - 'connect:DescribeQueue'
              - 'connect:GetContactAttributes'
              - 'connect:UpdateContactAttributes'
              - 'connect:StartTaskContact'
            Resource: 
              - !Ref ConnectInstanceARN
              - !Join
                - ''
                - - !Ref ConnectInstanceARN
                  - '/queue/*'
              - !Join
                - ''
                - - !Ref ConnectInstanceARN
                  - '/user/*'
              - !Join
                - ''
                - - !Ref ConnectInstanceARN
                  - '/contact-flow/*'
              - !Join
                - ''
                - - !Ref ConnectInstanceARN
                  - '/agent/*'
              - !Join
                - ''
                - - !Ref ConnectInstanceARN
                  - '/contact/*'
          - Effect: Allow
            Action:
              - 'ses:SendEmail'
              - 'ses:SendTemplatedEmail'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'transcribe:DeleteTranscriptionJob'
            Resource: 
              !Join
                - ''
                - - 'arn:aws:transcribe:'
                  - !Ref AWSRegion
                  - ':'
                  - !Ref AWS::AccountId
                  - ':transcription-job/*WLSConnectVoicemail3_*'
          - Effect: Allow
            Action:
              - 's3:GetObjectTagging'
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - !Ref WLSConnectVoicemailS3RecordingsBucketArn
              - !Join
                - ''
                - - !Ref WLSConnectVoicemailS3RecordingsBucketArn
                  - '/*'
              

          - Effect: Allow
            Action:
              - 's3:GetObjectTagging'
              - 's3:GetObject'
            Resource:
              !Join
                - ''
                - - !Ref WLSConnectVoicemailS3TranscriptsBucketArn
                  - '/*'
      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_Packager_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailPackagerRole

  WLSConnectVoicemailPresignerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: NonGuidedOptions
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:GeneratePresignedUrl'
            Resource:
              !Join
                - ''
                - - !Ref WLSConnectVoicemailS3RecordingsBucketArn
                  - '/*'
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Ref WLSConnectVoicemailPresignerAssumeRoleArn
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
            Resource: 
              - !Ref VoicemailKeyArn

      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_Presigner_Function_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailPresignerRole

  WLSConnectVoicemailSESPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: AWSEmailEnabled
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ses:GetEmailTemplate'
              - 'ses:UpdateEmailTemplate'
              - 'ses:CreateEmailTemplate'
              - 'ses:DeleteEmailTemplate'
            Resource: '*'
      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_SES_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailSESTemplateRole

  WLSConnectVoicemailTranscriberErrorPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:PutObject'
            Resource:
              !Join
                - ''
                - - !Ref WLSConnectVoicemailS3TranscriptsBucketArn
                  - '/*'
      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_Transcriber_Error_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailTranscriberErrorRole

  WLSConnectVoicemailTranscriberPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObjectTagging'
              - 's3:GetObject'
            Resource:
              !Join
                - ''
                - - !Ref WLSConnectVoicemailS3RecordingsBucketArn
                  - '/*'
          - Effect: Allow
            Action:
              - 'transcribe:StartTranscriptionJob'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:PutObjectTagging'
            Resource:
              !Join
                - ''
                - - !Ref WLSConnectVoicemailS3TranscriptsBucketArn
                  - '/*'
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:GenerateDataKey'
            Resource:
              - !Ref VoicemailKeyArn
              - !Ref WLSConnectVoicemailKVSStreamKMSVoicemailKeyArn
          - Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource:
              - !Ref WLSConnectVoicemailTranscriberRoleArn

      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_Transcriber_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailTranscriberRole
  
  WLSConnectVoicemailPackagerPolicyAddOn:
    Type: AWS::IAM::ManagedPolicy
    Condition: NonGuidedOptions
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'lambda:InvokeFunction'
            Resource: !Ref WLSConnectVoicemailPresignerArn
      ManagedPolicyName:
        !Join
          - ''
          - - 'WLSConnectVoicemail_Packager_AddOn_Policy_'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailPackagerRole