AWSTemplateFormatVersion: '2010-09-09'

Description: Deploys the Voicemail Express core components. Updated for 2024.09.01.

Parameters:
  ConnectInstanceAlias:
    Type: String
  ExpiredRecordingBehavior:
    Type: String
  EnableVMToConnectTask:
    Type: String
  EnableVMToConnectGuidedTask:
    Type: String
  EnableVMToEmail:
    Type: String
  RecordingsExpireInXDays:
    Type: String

Conditions:
  AudioDelete: !Equals
    - !Ref ExpiredRecordingBehavior
    - delete
  AudioGlacier: !Equals
    - !Ref ExpiredRecordingBehavior
    - glacier
  AudioLifecycle: !Or
    - !Equals
      - !Ref ExpiredRecordingBehavior
      - glacier
    - !Equals
      - !Ref ExpiredRecordingBehavior
      - delete
  ConnectTasksEnabled: !Equals
    - !Ref EnableVMToConnectTask
    - 'yes'
  ConnectGuidedTasksEnabled: !Equals
    - !Ref EnableVMToConnectGuidedTask
    - 'yes'
  AWSEmailEnabled: !Equals
    - !Ref EnableVMToEmail
    - 'yes'
  NonGuidedOptions: !Or
    - !Equals
      - !Ref EnableVMToConnectTask
      - 'yes'
    - !Equals
      - !Ref EnableVMToEmail
      - 'yes'

Resources:
  WLSConnectVoicemailKVStoS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ''
        - - WLSConnectVoicemail3_KVS_to_S3_Role_
          - !Ref ConnectInstanceAlias
      Description: Provides appropriate access for the KVS to S3 function.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WLSConnectVoicemailGuidedFlowPresignerRole:
    Type: AWS::IAM::Role
    Condition: ConnectGuidedTasksEnabled
    Properties:
      RoleName: !Join
        - ''
        - - WLSConnectVoicemail3_Guided_Flow_Role_
          - !Ref ConnectInstanceAlias
      Description: Provides appropriate access for the Guided Flow Presigner function.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WLSConnectVoicemailPackagerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ''
        - - WLSConnectVoicemail3_Packager_Role_
          - !Ref ConnectInstanceAlias
      Description: Provides appropriate access for the Packager function.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WLSConnectVoicemailPresignerRole:
    Type: AWS::IAM::Role
    Condition: NonGuidedOptions
    Properties:
      RoleName: !Join
        - ''
        - - WLSConnectVoicemail3_Presigner_Role_
          - !Ref ConnectInstanceAlias
      Description: Provides appropriate access for the Presigner function.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
              AWS:
                - !GetAtt WLSConnectVoicemailPresignerRole.Arn
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WLSConnectVoicemailSESTemplateRole:
    Type: AWS::IAM::Role
    Condition: AWSEmailEnabled
    Properties:
      RoleName: !Join
        - ''
        - - WLSConnectVoicemail3_SES_Template_Role_
          - !Ref ConnectInstanceAlias
      Description: Provides appropriate access for the SES Template tool function.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WLSConnectVoicemailTranscriberRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ''
        - - WLSConnectVoicemail3_Transcriber_Role_
          - !Ref ConnectInstanceAlias
      Description: Provides appropriate access for the Transcriber function.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - transcribe.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WLSConnectVoicemailTranscriberErrorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ''
        - - WLSConnectVoicemail3_Transcriber_Error_Role_
          - !Ref ConnectInstanceAlias
      Description: Provides appropriate access for the Transcriber function.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WLSConnectVoicemailS3RecordingsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - ''
        - - wlsconnectvoicemail-recordings-
          - !Ref ConnectInstanceAlias
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
            KMSMasterKeyID: !GetAtt WLSConnectVoicemailKMSS3Key.Arn     
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      LifecycleConfiguration: !If
        - AudioLifecycle
        - Rules:
            - Id: WLSConnectVoicemailS3DeletePolicy
              Status: !If
                - AudioDelete
                - Enabled
                - Disabled
              ExpirationInDays: !Ref RecordingsExpireInXDays
            - Id: WLSConnectVoicemailS3GlacierPolicy
              Status: !If
                - AudioGlacier
                - Enabled
                - Disabled
              Transitions:
                - TransitionInDays: !Ref RecordingsExpireInXDays
                  StorageClass: GLACIER
        - !Ref AWS::NoValue

  WLSConnectVoicemailKMSS3Key:
    Type: AWS::KMS::Key
    Properties:
      Description: 'Connect Voicemail Encryption Key'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: 'key-policy'
        Statement:
          - Sid: 'Enable IAM User Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: 'Allow Key Administration'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'

  WLSConnectVoicemailKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join 
        - ''
        - - 'alias/voicemail-key-'
          - !Ref ConnectInstanceAlias
      TargetKeyId: !Ref WLSConnectVoicemailKMSS3Key


  WLSConnectVoicemailS3TranscriptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - ''
        - - wlsconnectvoicemail-transcripts-
          - !Ref ConnectInstanceAlias
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
            KMSMasterKeyID: !GetAtt WLSConnectVoicemailKMSS3Key.Arn     
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  WLSConnectVoicemailPresignerAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn:
      - WLSConnectVoicemailS3RecordingsBucket
      - WLSConnectVoicemailS3TranscriptsBucket
      - WLSConnectVoicemailPresignerRole
    Condition: NonGuidedOptions
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Join
                - ''
                - - !GetAtt WLSConnectVoicemailS3RecordingsBucket.Arn
                  - /*
      ManagedPolicyName: !Join
        - ''
        - - WLSConnectVoicemail3_Presigner_Policy_
          - !Ref ConnectInstanceAlias
      Roles:
        - !Ref WLSConnectVoicemailPresignerRole

  # WLSConnectVoicemailPresignerUser:
  #   Type: AWS::IAM::User
  #   DependsOn:
  #     - WLSConnectVoicemailPresignerUserPolicy
  #   Condition: NonGuidedOptions
  #   Properties:
  #     UserName: !Join
  #       - ''
  #       - - WLSConnectVoicemail3_Presigner_User_
  #         - !Ref ConnectInstanceAlias
  #     ManagedPolicyArns:
  #       - !Ref WLSConnectVoicemailPresignerUserPolicy
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # WLSConnectVoicemailUserKey:
  #   Type: AWS::IAM::AccessKey
  #   DependsOn:
  #     - WLSConnectVoicemailPresignerUser
  #   Condition: NonGuidedOptions
  #   Properties:
  #     Status: Active
  #     UserName: !Ref WLSConnectVoicemailPresignerUser

  # WLSConnectVoicemailSecrets:
  #   Type: AWS::SecretsManager::Secret
  #   DependsOn:
  #     - WLSConnectVoicemailPresignerUser
  #     - WLSConnectVoicemailUserKey
  #   Condition: NonGuidedOptions
  #   Properties:
  #     Name: !Join
  #       - ''
  #       - - WLSConnectVoicemail3_Access_Secrets_
  #         - !Ref ConnectInstanceAlias
  #     Description: Stores user credentials for the presigner function
  #     SecretString: !Sub
  #       - '{"WLSConnectVoicemail_iam_key_id":"${KeyID}","WLSConnectVoicemail_iam_key_secret":"${KeySecret}"}'
  #       - KeyID: !Ref WLSConnectVoicemailUserKey
  #         KeySecret: !GetAtt WLSConnectVoicemailUserKey.SecretAccessKey

Outputs:
  WLSConnectVoicemailS3RecordingsBucket:
    Description: Voicemail Recording storage bucket name
    Value: !Ref WLSConnectVoicemailS3RecordingsBucket
  WLSConnectVoicemailS3RecordingsBuckettArn:
    Description: Voicemail Recording storage bucket ARN
    Value: !GetAtt WLSConnectVoicemailS3RecordingsBucket.Arn
  WLSConnectVoicemailS3TranscriptsBucket:
    Description: Voicemail Transcript storage bucket name
    Value: !Ref WLSConnectVoicemailS3TranscriptsBucket
  WLSConnectVoicemailS3TranscriptsBucketArn:
    Description: Voicemail Transcript storage bucket ARN
    Value: !GetAtt WLSConnectVoicemailS3TranscriptsBucket.Arn
  WLSConnectVoicemailSecrets:
    Description: Secrets ID
    Condition: NonGuidedOptions
    Value: !Ref WLSConnectVoicemailSecrets
  WLSConnectVoicemailGuidedFlowPresignerRole:
    Description: Guided flow presigner role name
    Condition: ConnectGuidedTasksEnabled
    Value: !Ref WLSConnectVoicemailGuidedFlowPresignerRole
  WLSConnectVoicemailGuidedFlowPresignerRoleArn:
    Description: Guided flow presigner role ARN
    Condition: ConnectGuidedTasksEnabled
    Value: !GetAtt WLSConnectVoicemailGuidedFlowPresignerRole.Arn
  WLSConnectVoicemailKVStoS3Role:
    Description: KVS to S3 role name
    Value: !Ref WLSConnectVoicemailKVStoS3Role
  WLSConnectVoicemailKVStoS3RoleArn:
    Description: KVS to S3 role ARN
    Value: !GetAtt WLSConnectVoicemailKVStoS3Role.Arn
  WLSConnectVoicemailPackagerRole:
    Description: Packager role name
    Value: !Ref WLSConnectVoicemailPackagerRole
  WLSConnectVoicemailPackagerRoleArn:
    Description: Packager role ARN
    Value: !GetAtt WLSConnectVoicemailPackagerRole.Arn
  WLSConnectVoicemailPresignerRole:
    Description: Presigner role name
    Condition: NonGuidedOptions
    Value: !Ref WLSConnectVoicemailPresignerRole
  WLSConnectVoicemailPresignerRoleArn:
    Description: Presigner role ARN
    Condition: NonGuidedOptions
    Value: !GetAtt WLSConnectVoicemailPresignerRole.Arn
  WLSConnectVoicemailSESTemplateRole:
    Description: SES Template role name
    Condition: AWSEmailEnabled
    Value: !Ref WLSConnectVoicemailSESTemplateRole
  WLSConnectVoicemailSESTemplateRoleArn:
    Description: SES Template role ARN
    Condition: AWSEmailEnabled
    Value: !GetAtt WLSConnectVoicemailSESTemplateRole.Arn
  WLSConnectVoicemailTranscriberRole:
    Description: Transcriber role name
    Value: !Ref WLSConnectVoicemailTranscriberRole
  WLSConnectVoicemailTranscriberRoleArn:
    Description: Transcriber role ARN
    Value: !GetAtt WLSConnectVoicemailTranscriberRole.Arn
  WLSConnectVoicemailTranscriberErrorRole:
    Description: Transcriber error handler role name
    Value: !Ref WLSConnectVoicemailTranscriberErrorRole
  WLSConnectVoicemailTranscriberErrorRoleArn:
    Description: Transcriber error handler role ARN
    Value: !GetAtt WLSConnectVoicemailTranscriberErrorRole.Arn
  VoicemailKeyArn:
    Description: 'KMS Key ARN'
    Value: !GetAtt WLSConnectVoicemailKMSS3Key.Arn