AWSTemplateFormatVersion: "2010-09-09"

Description: Deploys the Voicemail Express Lambda functions. Updated for 2024.09.01.

Parameters:
  EXPTemplateVersion:
    Type: String
  AWSRegion:
    Type: String
  ConnectInstanceAlias:
    Type: String
  EnableVMToConnectTask:
    Type: String
  EnableVMToConnectGuidedTask:
    Type: String
  EnableVMToEmail:
    Type: String
  EXPDevBucketPrefix:
    Type: String
  LambdaLoggingLevel:
    Type: String
  RecordingsExpireInXDays:
    Type: String
  VMEmailDefaultAgentTemplate:
    Type: String
  VMEmailDefaultQueueTemplate:
    Type: String
  VMDefaultMode:
    Type: String
  VMToEmailDefaultFrom:
    Type: String
  VMToEmailDefaultTo:
    Type: String
  WLSConnectVoicemailDefaultTaskFlow:
    Type: String
  WLSConnectVoicemailDefaultGuidedTaskFlow:
    Type: String
  WLSConnectVoicemailSecrets:
    Type: String
  WLSConnectVoicemailS3RecordingsBucket:
    Type: String
  WLSConnectVoicemailS3TranscriptsBucket:
    Type: String
  VMAgentAddressKey:
    Type: String
  WLSConnectVoicemailKVStoS3RoleArn:
    Type: String
  WLSConnectVoicemailKVStoS3Role:
    Type: String
  WLSConnectVoicemailPackagerRoleArn:
    Type: String
  WLSConnectVoicemailPackagerRole:
    Type: String
  WLSConnectVoicemailPresignerRoleArn:
    Type: String
  WLSConnectVoicemailPresignerRole:
    Type: String
  WLSConnectVoicemailTranscriberRoleArn:
    Type: String
  WLSConnectVoicemailTranscriberRole:
    Type: String
  WLSConnectVoicemailTranscriberErrorRoleArn:
    Type: String
  WLSConnectVoicemailTranscriberErrorRole:
    Type: String
  TaskRecordingLinksExpireInXDays:
    Type: String
  EmailRecordingLinksExpireInXDays:
    Type: String

Mappings:
  TZInfo:
    us-east-1:
      TZvalue: 'America/New_York'
    us-west-2:
      TZvalue: 'America/Los_Angeles'
    af-south-1:
      TZvalue: 'Africa/Johannesburg'
    ap-southeast-1:
      TZvalue: 'Asia/Singapore'
    ap-southeast-2:
      TZvalue: 'Australia/Sydney'
    ap-northeast-1:
      TZvalue: 'Asia/Tokyo'
    ap-northeast-2:
      TZvalue: 'Asia/Seoul'
    ca-central-1:
      TZvalue: 'Canada/Central'
    eu-central-1:
      TZvalue: 'Europe/Berlin'
    eu-west-2:
      TZvalue: 'Europe/London'
  VMModes:
    AmazonConnectTask:
      mode: task
    AmazonConnectGuidedTask:
      mode: guided_task
    AmazonSimpleEmailService:
      mode: email

Conditions:
  ConnectTasksEnabled: !Equals 
    - !Ref EnableVMToConnectTask
    - 'yes'
  ConnectGuidedTasksEnabled: !Equals
    - !Ref EnableVMToConnectGuidedTask
    - 'yes'
  AWSEmailEnabled: !Equals
    - !Ref EnableVMToEmail
    - 'yes'
  NonGuidedOptions: !Or
    - !Equals
      - !Ref EnableVMToConnectTask
      - 'yes'
    - !Equals
      - !Ref EnableVMToEmail
      - 'yes'

Resources:
  # WLSConnectVoicemailPythonLayer:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     CompatibleRuntimes:
  #       - python3.12
  #     Content:
  #       S3Bucket:
  #         !Join
  #           - ''
  #           - - !Ref EXPDevBucketPrefix
  #             - 'WLSConnectVoicemail-source-'
  #             - !Ref AWSRegion
  #       S3Key:
  #         !Join
  #         - ''
  #         - - 'WLSConnectVoicemail3/'
  #           - !Ref EXPTemplateVersion
  #           - /zip/WLSConnectVoicemail3_common_python.zip
  #     Description: Provides dependencies code and functions for AWS Lambda functions that power Voicemail Express.
  #     LayerName: !Join
  #       - ''
  #       - - 'common_python_layer_'
  #         - !Ref ConnectInstanceAlias
  #     LicenseInfo: https://aws.amazon.com/apache-2-0

  WLSConnectVoicemailPresigner:
    Type: AWS::Lambda::Function
    Condition: NonGuidedOptions
    Properties:
      Code:
        S3Bucket:
          !Ref EXPDevBucketPrefix
        S3Key:
          'WLSConnectVoicemail3_presigner.zip'
      Description: Generates the presigned URL that provides authenticated access to the voicemail recording in S3. Used for Task and EMail deliivery modes.
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          tasks_url_expire:
            Ref: TaskRecordingLinksExpireInXDays
          email_url_expire:
            Ref: EmailRecordingLinksExpireInXDays
          secrets_key_id:
            Ref: WLSConnectVoicemailSecrets
          package_version:
            Ref: EXPTemplateVersion
      FunctionName:
        !Join
            - ''
            - - 'WLSConnectVoicemail3-Presigner-'
              - !Ref ConnectInstanceAlias
      Handler: WLSConnectVoicemail3_presigner.lambda_handler
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Role: !Ref WLSConnectVoicemailPresignerRoleArn
      Runtime: python3.12
      Timeout: 30

  WLSConnectVoicemailPackager:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Ref EXPDevBucketPrefix
        S3Key:
          'WLSConnectVoicemail3_packager.zip'
      Description: Packages the voicemail and creates a task in Amazon Connect.
      Environment:
        Variables:
          s3_recordings_bucket:
            Ref: WLSConnectVoicemailS3RecordingsBucket
          s3_transcripts_bucket:
            Ref: WLSConnectVoicemailS3TranscriptsBucket
          presigner_function_arn:
            !If [NonGuidedOptions, !Ref WLSConnectVoicemailPresigner, 'AWS::NoValue']
          default_task_flow:
            !If [ConnectTasksEnabled, !Ref WLSConnectVoicemailDefaultTaskFlow, 'AWS::NoValue']
          default_guided_task_flow:
            !If [ConnectGuidedTasksEnabled, !Ref WLSConnectVoicemailDefaultGuidedTaskFlow, 'AWS::NoValue']
          package_version:
            Ref: EXPTemplateVersion
          TZ:
            !FindInMap [TZInfo, !Ref "AWS::Region", TZvalue]
          default_email_from:
            !If [AWSEmailEnabled, !Ref VMToEmailDefaultFrom, 'AWS::NoValue']
          default_email_target:
            !If [AWSEmailEnabled, !Ref VMToEmailDefaultTo, 'AWS::NoValue']
          default_WLSConnectVoicemail_mode:
            !FindInMap [VMModes, !Ref "VMDefaultMode", mode]
          default_agent_email_template:
            !If [AWSEmailEnabled, !Ref VMEmailDefaultAgentTemplate, 'AWS::NoValue']
          default_queue_email_template:
            !If [AWSEmailEnabled, !Ref VMEmailDefaultQueueTemplate, 'AWS::NoValue']
          agent_email_key:
            !If [AWSEmailEnabled, !Ref VMAgentAddressKey, 'Email']
      FunctionName:
        !Join
            - ''
            - - 'WLSConnectVoicemail3-Packager-'
              - !Ref ConnectInstanceAlias
      Handler: WLSConnectVoicemail3_packager.lambda_handler
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Role: !Ref WLSConnectVoicemailPackagerRoleArn
      Layers: ['arn:aws:lambda:us-east-1:209479304522:layer:common_python_layer_bolerotest:1']
      Runtime: python3.12
      Timeout: 900

  WLSConnectVoicemailTranscriber:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Ref EXPDevBucketPrefix
        S3Key:
          'WLSConnectVoicemail3_transcriber.zip'
      Description: Transcribes the voicemail to text and stores the transcription in S3
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          s3_transcripts_bucket:
            Ref: WLSConnectVoicemailS3TranscriptsBucket
          package_version:
            Ref: EXPTemplateVersion
          role_arn:
            Ref: WLSConnectVoicemailTranscriberRoleArn
      FunctionName:
        !Join
            - ''
            - - 'WLSConnectVoicemail3-Transcriber-'
              - !Ref ConnectInstanceAlias
      Handler: WLSConnectVoicemail3_transcriber.lambda_handler
      Role: !Ref WLSConnectVoicemailTranscriberRoleArn
      Runtime: python3.12
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Timeout: 900

  WLSConnectVoicemailKVStoS3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Ref EXPDevBucketPrefix
        S3Key:
          'WLSConnectVoicemail3_kvs_to_s3.zip'
      Description: Extracts the voicemail from the KVS stream and writes it to S3 with tag data
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          s3_recordings_bucket:
            Ref: WLSConnectVoicemailS3RecordingsBucket
          package_version:
            Ref: EXPTemplateVersion
      FunctionName:
        !Join
            - ''
            - - 'WLSConnectVoicemail3-KVStoS3-'
              - !Ref ConnectInstanceAlias
      Handler: WLSConnectVoicemail3_kvs_to_s3.lambda_handler
      Role: !Ref WLSConnectVoicemailKVStoS3RoleArn
      Layers: ['arn:aws:lambda:us-east-1:209479304522:layer:common_python_layer_bolerotest:1']
      Runtime: python3.12
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Timeout: 900

  WLSConnectVoicemailTranscribeErrorHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Ref EXPDevBucketPrefix
        S3Key:
          'WLSConnectVoicemail3_transcription_error_handler.zip'
      Description: Catches transcription errors due to corrupt wav files and provides a notification transcript so that processing completes
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          s3_transcripts_bucket:
            Ref: WLSConnectVoicemailS3TranscriptsBucket
          package_version:
            Ref: EXPTemplateVersion
      FunctionName:
        !Join
            - ''
            - - 'WLSConnectVoicemail3-TranscribeErrorHandler-'
              - !Ref ConnectInstanceAlias
      Handler: WLSConnectVoicemail3_transcription_error_handler.lambda_handler
      Role: !Ref WLSConnectVoicemailTranscriberErrorRoleArn
      Runtime: python3.12
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Timeout: 30

Outputs:
  WLSConnectVoicemailPackagerArn:
    Description: ARN of the Packager function
    Value: !GetAtt WLSConnectVoicemailPackager.Arn
  WLSConnectVoicemailTranscriberArn:
    Description: ARN of the Transcriber function
    Value: !GetAtt WLSConnectVoicemailTranscriber.Arn
  WLSConnectVoicemailKVStoS3:
    Description: Name of the KVS to S3 function
    Value: !Ref WLSConnectVoicemailKVStoS3
  WLSConnectVoicemailTranscribeErrorArn:
    Description: ARN of the transcribe error handler function
    Value: !GetAtt WLSConnectVoicemailTranscribeErrorHandler.Arn
  WLSConnectVoicemailPresignerArn:
    Description: ARN of the presigner function
    Condition: NonGuidedOptions
    Value: !GetAtt WLSConnectVoicemailPresigner.Arn