AWSTemplateFormatVersion: "2010-09-09"

Description: Deploys the Voicemail Express content triggers. Updated for 2024.09.01

Parameters:
  EXPTemplateVersion:
    Type: String
  ConnectCTRStreamARN:
    Type: String
  WLSConnectVoicemailS3RecordingsBucket:
    Type: String
  WLSConnectVoicemailS3TranscriptsBucket:
    Type: String
  WLSConnectVoicemailS3RecordingsBucketArn:
    Type: String
  WLSConnectVoicemailPackagerArn:
    Type: String
  WLSConnectVoicemailS3TranscriptsBucketArn:
    Type: String
  WLSConnectVoicemailTranscriberArn:
    Type: String
  WLSConnectVoicemailKVStoS3:
    Type: String
  ConnectInstanceAlias:
    Type: String
  WLSConnectVoicemailTranscribeErrorArn:
    Type: String
  ConnectInstanceARN:
    Type: String
  WLSConnectVoicemailGuidedFlowPresignerArn:
    Type: String
  EnableVMToConnectGuidedTask:
    Type: String

Conditions:
  ConnectGuidedTasksEnabled: !Equals
    - !Ref EnableVMToConnectGuidedTask
    - 'yes'

Resources:

  IntegrationAssociation:
    Type: AWS::Connect::IntegrationAssociation
    Condition: ConnectGuidedTasksEnabled
    Properties:
      InstanceId: !Ref ConnectInstanceARN
      IntegrationType: LAMBDA_FUNCTION
      IntegrationArn: !Ref WLSConnectVoicemailGuidedFlowPresignerArn

  RecordingsBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WLSConnectVoicemailTranscriberArn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Ref WLSConnectVoicemailS3RecordingsBucketArn

  TranscriptsBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WLSConnectVoicemailPackagerArn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Ref WLSConnectVoicemailS3TranscriptsBucketArn

  CTRStreamMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      BisectBatchOnFunctionError: true
      Enabled: true
      EventSourceArn: !Ref ConnectCTRStreamARN
      FunctionName: !Ref WLSConnectVoicemailKVStoS3
      MaximumRetryAttempts: 3
      StartingPosition: LATEST
      FilterCriteria:
        Filters:
          - Pattern: "{    \"data\":{        \"Attributes\":{            \"WLSConnectVoicemail3_flag\":[\"1\"]        },        \"Recordings\":{            \"StorageType\":[\"KINESIS_VIDEO_STREAM\"]        },        \"Agent\":[null]    }}"

  TranscriberRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref WLSConnectVoicemailS3RecordingsBucket
      Name: !Join [ "-", [ wls,!Ref ConnectInstanceAlias,TranscriberRule ] ]
      State: ENABLED
      Targets:
        - Id: !Join [ "-", [ !Ref ConnectInstanceAlias,TranscriberFunction ] ]
          Arn: !Ref WLSConnectVoicemailTranscriberArn

  TrasncriberLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref WLSConnectVoicemailTranscriberArn
      Principal: events.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt TranscriberRule.Arn

  PackagerRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref WLSConnectVoicemailS3TranscriptsBucket
      Name: !Join [ "-", [ wls,!Ref ConnectInstanceAlias,PackagerRule ] ]
      State: ENABLED
      Targets: 
        - Id: !Join [ "-", [ !Ref ConnectInstanceAlias,PackagerFunction ] ]
          Arn: !Ref WLSConnectVoicemailPackagerArn
          
  PackagerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref WLSConnectVoicemailPackagerArn
      Principal: events.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt PackagerRule.Arn

  TranscribeErrorRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern: {
          "source": ["aws.transcribe"],
          "detail-type": ["Transcribe Job State Change"],
          "detail": {
            "TranscriptionJobName": [{
              "prefix": "WLSConnectVoicemail3_"
            }],
            "TranscriptionJobStatus": ["FAILED"]
          }
        }
      Name: !Join [ "-", [ wls,!Ref ConnectInstanceAlias,TranscribeErrorRule ] ]
      State: ENABLED
      Targets: 
        - Id: !Join [ "-", [ !Ref ConnectInstanceAlias,TranscribeErrorFunction ] ]
          Arn: !Ref WLSConnectVoicemailTranscribeErrorArn
  
  TranscriberErrorLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref WLSConnectVoicemailTranscribeErrorArn
      Principal: events.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt TranscribeErrorRule.Arn